### ISSUE TITLE
The plugin breaks import statements

### ISSUE THREAD

**Issue by coolov** [MatAtBread/webpack-async-await#2]
After enabling the plugin, `import` statements are no longer transpiled. 

I get this runtime error:
`bundle.js:72 Uncaught SyntaxError: Unexpected token import`

**Comment by coolov** [comment]
Nevermind. I was way too quick to report this issue. Upgrading webpack solved it. Thanks for an excellent plugin!

**Comment by matAtWork** [comment]
NP
