### ISSUE TITLE
Unexpected token: name (wait)

### ISSUE THREAD

**Issue by fresheneesz** [MatAtBread/webpack-async-await#3]
When using this plugin, I no longer get a failure to build (ie `Module parse failed: The keyword 'await' is reserved (13:8)`), but I am getting the following console log: `Unexpected token: name (wait)`

The full output is:

```
building and minifying...
rpepCore.umd.js from UglifyJs
Unexpected token: name (wait) [rpepCore.umd.js:92,14]
Thu Oct 26 2017 23:05:16 GMT-0700 (Pacific Daylight Time) - Done building rpepCore!
```

The bundle is generated, but still contains the `await ayncFunction()` line rather than having it converted to promises. Is this expected. Does this module simply ignore the warning and print out the code as is? I was hoping it would convert it.

**Comment by fresheneesz** [comment]
I guess I misunderstood the purpose of this plugin.

**Comment by matAtWork** [comment]
To convert it async/await to Promises, you need a pre-compile step like nodent. Your choices are the webpack loader https://github.com/MatAtWork/nodent-loader, which transforms during packing, or https://github.com/MatAtBread/nodent which transforms loading into Node.

**Comment by fresheneesz** [comment]
@matAtWork Thanks for the tip! Unfortunately adding that didn't seem to work for me : ( . I have an SO question open with my config on there if you'd like to help me out a bit more: https://stackoverflow.com/questions/46970787/how-to-use-webpack-to-transform-the-await-keyword-to-es5?noredirect=1#comment80888936_46970787 : D

**Comment by fresheneesz** [comment]
Actually looks like I got it working. Thanks!
